name: gymgenius_v1
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  device_preview_plus: ^2.3.3
  # Utility Packages
  http: ^1.3.0
  # intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^6.1.3
  lottie: ^3.3.1
  carousel_slider: ^5.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product Specific
  # readmore: ^3.0.0
  # carousel_slider: ^5.0.0
  # flutter_rating_bar: ^4.0.1
  # capped_progress_indicator: ^0.0.2

  # Firebase
  # firebase_core: ^2.30.1
  # firebase_auth: ^4.19.4
  # cloud_firestore: ^4.17.2
  # firebase_storage: ^11.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/fonts/
    - assets/images/animations/
    - assets/images/onboarding/
    - assets/images/banner/
    - assets/images/login_signup_verify/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 