// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdpl1x4MUVqhDRfgZQsv2VCVazIDlBr8s',
    appId: '1:466420273349:web:6f8a356b39f4c2575f20ac',
    messagingSenderId: '466420273349',
    projectId: 'gymgeniusv1',
    authDomain: 'gymgeniusv1.firebaseapp.com',
    storageBucket: 'gymgeniusv1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRmPZq2-HRpHbQmEg-DeTTNZOumcT-Yg',
    appId: '1:466420273349:android:70cbcd2ca17a83e65f20ac',
    messagingSenderId: '466420273349',
    projectId: 'gymgeniusv1',
    storageBucket: 'gymgeniusv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArh6JQnDFdyX05vqDsknpsXxGgj4nMYtA',
    appId: '1:466420273349:ios:6cbb40897544aa755f20ac',
    messagingSenderId: '466420273349',
    projectId: 'gymgeniusv1',
    storageBucket: 'gymgeniusv1.firebasestorage.app',
    iosBundleId: 'com.ak.gymgeniusv1',
  );
}
